description: Welcome to Better Computing. The student-run website for students in the School of Computing.

sass:
   sourcemap: true

url: "https://bettercomputing.info" # update previous line
domain: "bettercomputing.info" # update next line
baseurl: "/" # does not include hostname

collections:
    sections:
    pages:
        output: true
        permalink: "/:path"

defaults:
    - scope:
        path: ""
        type: "sections"
      values:
        pinned: false # by default, not pinned
        semester: 100 # "Other" stuff is pushed to the end
        archived: false
        course-acronym: ""
        layout: "section"
        learn: true

    - scope:
        path: "" # an empty string here means all files in the project
        type: "pages"
      values:
        layout: "frontpage"
        show-archived: false
